---

- hosts: nsapoold05
  tasks:

  - name: update apt repo
    apt: update_cache=yes
  - name: Install packages from task06
    apt:
      pkg:
        - vim
        - git
        - tree
        - htop
        - curl
        - emacs
        - net-tools
        - sudo
        - make
        - unzip
        - python3
        - python3-pip
