---

- hosts: nsapoold05
  tasks:

  - name: Install php7.3 and modules
    apt:
      name:
        - php7.3
        - php7.3-cli
        - php7.3-fpm
        - php7.3-json
        - php7.3-pdo
        - php7.3-mysql
        - php7.3-zip
        - php7.3-gd 
        - php7.3-mbstring
        - php7.3-curl
        - php7.3-xml
        - php-pear
        - php7.3-bcmath
        - php7.3-intl
  - name: set timezone to Europe/Paris in fpm/php.ini
    ini_file:
      dest: /etc/php/7.3/{{ item.location }}/php.ini
      section: Date
      option: "{{ item.option }}"   
      value: "{{ item.val }}"
    with_items:
     - { location: fpm, option: date.timezone, val: Europe/Paris }
     - { location: cli, option: date.timezone, val: Europe/Paris }


